### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by lhunath** [adtrevor/OneAxisGeometryReader#6]
It would be great if you could tag a release so we can target a major version of the dependency in SPM.

**Comment by PopFlamingo** [comment]
@lhunath Hi! Thanks for the issue and sorry for the delay! I have released version `1.0.0` with API name changes (however the previous names can still be used for now as they have just been deprecated).

**Comment by PopFlamingo** [comment]
The new names are `HGeometryReader` and `VGeometryReader`
